# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  systemlibrary-app:
    image: systemlibrary
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://systemlibrary-postgresql:5432/systemlibrary
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://systemlibrary-postgresql:5432/systemlibrary
      - JHIPSTER_CACHE_REDIS_SERVER=redis://systemlibrary-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://systemlibrary-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_ELASTICSEARCH_URIS=http://systemlibrary-elasticsearch:9200
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8080:8080
    depends_on:
      - systemlibrary-postgresql
      - systemlibrary-redis
      - systemlibrary-elasticsearch
  systemlibrary-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/SystemLibrary/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=systemlibrary
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 5432:5432
  systemlibrary-redis:
    image: redis:6.2.7
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 6379:6379
    command: ['redis-server', '--notify-keyspace-events', 'Ex']
  systemlibrary-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    # volumes:
    #   - ~/volumes/jhipster/SystemLibrary/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
